// <auto-generated />
namespace Ajf.CoreSolver.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCalculationStatusToCalculation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCalculationStatusToCalculation));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041213581_AddCalculationStatusToCalculation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
